# Regression Problem

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]] , columns=['cgpa','profile_score','lpa'])

In [5]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [23]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters={}
    L = len(layer_dims)
    for l in range(1,L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1] , layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[1],1))

    return parameters

In [24]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.],
        [0.]])}

In [25]:
def linear_forward(A_prev , W , b):
    Z = np.dot(W.T, A_prev) + b
    return Z

In [32]:
# This is the main function for forward propagation 
def L_layer_forward(X, parameters):
    A = X
    L = len(parameters) // 2    # Number of layers in the neural network
    for  l in range(1 , L+1):
        A_prev = A
        w1 = parameters['W' + str(1)]
        b1 = parameters['b' + str(1)]

        print('A' +str(l-1) +":", A_prev)
        print("W" + str(l)+":",w1)
        print("b"+str(l)+":",b1)
        print("--"*20)

        A = linear_forward(A_prev , w1 , b1)
        print("A" + str(l)+":",A)
        print("**"*20)

    return A,A_prev

In [36]:
X = df[['cgpa' , 'profile_score']].values[0].reshape(2,1)  # Shape(no of features , no  of triaining example)
y = df[['lpa']].values[0][0]

# Paramter initialization
parameters = initialize_parameters([2,2,1])
# X
# L_layer_forward(X, parameters)
y_hat,A1 = L_layer_forward(X, parameters)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1 0.1]
 [0.1 0.1]]
b2: [[0.]
 [0.]]
----------------------------------------
A2: [[0.32]
 [0.32]]
****************************************

In [37]:
y

np.int64(4)

In [38]:
y_hat = y_hat[0][0]

In [39]:
A1

array([[1.6],
       [1.6]])

In [42]:
update_parameters(parameters,y,y_hat,A1,X)

In [41]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [43]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1 0.1]
 [0.1 0.1]]
b2: [[0.]
 [0.]]
----------------------------------------
A2: [[0.32]
 [0.32]]
****************************************

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136],
        [0.      ]])}

In [44]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0: [[7]
 [9]]
W1: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1: [[0.00082267]
 [0.00082267]]
----------------------------------------
A1: [[1.70612461]
 [1.70612461]]
****************************************
A1: [[1.70612461]
 [1.70612461]]
W2: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b2: [[0.00082267]
 [0.00082267]]
----------------------------------------
A2: [[0.36450487]
 [0.36450487]]
****************************************

{'W1': array([[0.1148618 , 0.11722763],
        [0.1148618 , 0.11722763]]),
 'b1': array([[0.00200559],
        [0.00200559]]),
 'W2': array([[0.12759346],
        [0.12759346]]),
 'b2': array([[0.13686445],
        [0.        ]])}

In [45]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0: [[ 6]
 [10]]
W1: [[0.1148618  0.11722763]
 [0.1148618  0.11722763]]
b1: [[0.00200559]
 [0.00200559]]
----------------------------------------
A1: [[1.83979431]
 [1.87764768]]
****************************************
A1: [[1.83979431]
 [1.87764768]]
W2: [[0.1148618  0.11722763]
 [0.1148618  0.11722763]]
b2: [[0.00200559]
 [0.00200559]]
----------------------------------------
A2: [[0.42899765]
 [0.43779251]]
****************************************

{'W1': array([[0.12476208, 0.1337281 ],
        [0.12479027, 0.13377509]]),
 'b1': array([[0.00365564],
        [0.00366034]]),
 'W2': array([[0.14809246],
        [0.14851422]]),
 'b2': array([[0.15965623],
        [0.        ]])}

In [46]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0: [[ 5]
 [12]]
W1: [[0.12476208 0.1337281 ]
 [0.12479027 0.13377509]]
b1: [[0.00365564]
 [0.00366034]]
----------------------------------------
A1: [[2.12494929]
 [2.27760195]]
****************************************
A1: [[2.12494929]
 [2.27760195]]
W2: [[0.12476208 0.1337281 ]
 [0.12479027 0.13377509]]
b2: [[0.00365564]
 [0.00366034]]
----------------------------------------
A2: [[0.55299129]
 [0.59251218]]
****************************************

{'W1': array([[0.13607604, 0.1608816 ],
        [0.13625832, 0.1612984 ]]),
 'b1': array([[0.00591843],
        [0.00595394]]),
 'W2': array([[0.17549159],
        [0.17788166]]),
 'b2': array([[0.19077568],
        [0.        ]])}

In [47]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1 0.1]
 [0.1 0.1]]
b2: [[0.]
 [0.]]
----------------------------------------
A2: [[0.32]
 [0.32]]
****************************************
A0: [[7]
 [9]]
W1: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1: [[0.00082267]
 [0.00082267]]
----------------------------------------
A1: [[1.70612461]
 [1.70612461]]
****************************************
A1: [[1.70612461]
 [1.70612461]]
W2: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b2: [[0.00082267]
 [0.00082267]]
----------------------------------------
A2: [[0.36450487]
 [0.36450487]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.1148618  0.11722763]
 [0.1148618  0.11722763]]
b1: [[0.00200559]
 [0.00200559]]
----------------------------------------
A1: [[1.83979431]
 [1.87764768]]
****************************************
A1: [[1.83979431]
 [1.87764768]]
W2: [[0.1148618  0.11722763]
 [0.1148618  0.11722763]]
b2: [[0.00200559]
 [0.00200559]]
----------------------------------------
A2: [[0.42899765]
 [0.43779251]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.12476208 0.1337281 ]
 [0.12479027 0.13377509]]
b1: [[0.00365564]
 [0.00366034]]
----------------------------------------
A1: [[2.12494929]
 [2.27760195]]
****************************************
A1: [[2.12494929]
 [2.27760195]]
W2: [[0.12476208 0.1337281 ]
 [0.12479027 0.13377509]]
b2: [[0.00365564]
 [0.00366034]]
----------------------------------------
A2: [[0.55299129]
 [0.59251218]]
****************************************
Epoch -  1 Loss -  26.907550899777384
A0: [[8]
 [8]]
W1: [[0.13607604 0.1608816 ]
 [0.13625832 0.1612984 ]]
b1: [[0.00591843]
 [0.00595394]]
----------------------------------------
A1: [[2.18459326]
 [2.58339397]]
****************************************
A1: [[2.18459326]
 [2.58339397]]
W2: [[0.13607604 0.1608816 ]
 [0.13625832 0.1612984 ]]
b2: [[0.00591843]
 [0.00595394]]
----------------------------------------
A2: [[0.65519814]
 [0.77411213]]
****************************************
A0: [[7]
 [9]]
W1: [[0.14624989 0.17105545]
 [0.14670285 0.17174294]]
b1: [[0.00719016]
 [0.00725951]]
----------------------------------------
A1: [[2.35126505]
 [2.75033412]]
****************************************
A1: [[2.35126505]
 [2.75033412]]
W2: [[0.14624989 0.17105545]
 [0.14670285 0.17174294]]
b2: [[0.00719016]
 [0.00725951]]
----------------------------------------
A2: [[0.75454427]
 [0.88180668]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.15873569 0.18710863]
 [0.15969068 0.18844157]]
b1: [[0.00897385]
 [0.00911491]]
----------------------------------------
A1: [[2.55829475]
 [3.01618236]]
****************************************
A1: [[2.55829475]
 [3.01618236]]
W2: [[0.15873569 0.18710863]
 [0.15969068 0.18844157]]
b2: [[0.00897385]
 [0.00911491]]
----------------------------------------
A2: [[0.89672273]
 [1.05616806]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.17319928 0.21121461]
 [0.17495771 0.21388663]]
b1: [[0.01138444]
 [0.01165942]]
----------------------------------------
A1: [[2.97687343]
 [3.63437207]]
****************************************
A1: [[2.97687343]
 [3.63437207]]
W2: [[0.17319928 0.21121461]
 [0.17495771 0.21388663]]
b2: [[0.01138444]
 [0.01165942]]
----------------------------------------
A2: [[1.16283821]
 [1.41776219]]
****************************************
Epoch -  2 Loss -  22.3318726301909
A0: [[8]
 [8]]
W1: [[0.18901416 0.24917032]
 [0.19198647 0.25475565]]
b1: [[0.01454742]
 [0.01506517]]
----------------------------------------
A1: [[3.06255246]
 [4.04647291]]
****************************************
A1: [[3.06255246]
 [4.04647291]]
W2: [[0.18901416 0.24917032]
 [0.19198647 0.25475565]]
b2: [[0.01454742]
 [0.01506517]]
----------------------------------------
A2: [[1.37028125]
 [1.80902417]]
****************************************
A0: [[7]
 [9]]
W1: [[0.20109158 0.26124775]
 [0.20515662 0.26792579]]
b1: [[0.0160571 ]
 [0.01671144]]
----------------------------------------
A1: [[3.27010773]
 [4.25677778]]
****************************************
A1: [[3.27010773]
 [4.25677778]]
W2: [[0.20109158 0.26124775]
 [0.20515662 0.26792579]]
b2: [[0.0160571 ]
 [0.01671144]]
----------------------------------------
A2: [[1.54695436]
 [2.01152026]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.21605969 0.28049245]
 [0.22170962 0.28920822]]
b1: [[0.0181954 ]
 [0.01907615]]
----------------------------------------
A1: [[3.53164969]
 [4.59411307]]
****************************************
A1: [[3.53164969]
 [4.59411307]]
W2: [[0.21605969 0.28049245]
 [0.22170962 0.28920822]]
b2: [[0.0181954 ]
 [0.01907615]]
----------------------------------------
A2: [[1.79980158]
 [2.3383325 ]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.23316085 0.30899438]
 [0.24091304 0.32121392]]
b1: [[0.02104559]
 [0.02227673]]
----------------------------------------
A1: [[4.07780628]
 [5.42181571]]
****************************************
A1: [[4.07780628]
 [5.42181571]]
W2: [[0.23316085 0.30899438]
 [0.24091304 0.32121392]]
b2: [[0.02104559]
 [0.02227673]]
----------------------------------------
A2: [[2.27801645]
 [3.02385865]]
****************************************
Epoch -  3 Loss -  14.694435066287255
A0: [[8]
 [8]]
W1: [[0.25100066 0.35180992]
 [0.26132172 0.37019476]]
b1: [[0.02461355]
 [0.02635846]]
----------------------------------------
A1: [[4.12319258]
 [5.80239597]]
****************************************
A1: [[4.12319258]
 [5.80239597]]
W2: [[0.25100066 0.35180992]
 [0.26132172 0.37019476]]
b2: [[0.02461355]
 [0.02635846]]
----------------------------------------
A2: [[2.5758297 ]
 [3.62495514]]
****************************************
A0: [[7]
 [9]]
W1: [[0.25987717 0.36068644]
 [0.27154688 0.38041992]]
b1: [[0.02572312]
 [0.02763661]]
----------------------------------------
A1: [[4.28878518]
 [5.97622094]]
****************************************
A1: [[4.28878518]
 [5.97622094]]
W2: [[0.25987717 0.36068644]
 [0.27154688 0.38041992]]
b2: [[0.02572312]
 [0.02763661]]
----------------------------------------
A2: [[2.7631046 ]
 [3.84801674]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.27267732 0.37714378]
 [0.28643693 0.39956427]]
b1: [[0.02755171]
 [0.02976376]]
----------------------------------------
A1: [[4.52798492]
 [6.28826913]]
****************************************
A1: [[4.52798492]
 [6.28826913]]
W2: [[0.27267732 0.37714378]
 [0.28643693 0.39956427]]
b2: [[0.02755171]
 [0.02976376]]
----------------------------------------
A2: [[3.06342301]
 [4.25003277]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.28801782 0.40271128]
 [0.3044934  0.42965839]]
b1: [[0.03010846]
 [0.03277317]]
----------------------------------------
A1: [[5.12411833]
 [7.20223019]]
****************************************
A1: [[5.12411833]
 [7.20223019]]
W2: [[0.28801782 0.40271128]
 [0.3044934  0.42965839]]
b2: [[0.03010846]
 [0.03277317]]
----------------------------------------
A2: [[3.6989774]
 [5.190812 ]]
****************************************
Epoch -  4 Loss -  6.638049183540845
A0: [[8]
 [8]]
W1: [[0.30350483 0.43988009]
 [0.3229775  0.47402023]]
b1: [[0.03320586]
 [0.03646999]]
----------------------------------------
A1: [[5.04506448]
 [7.34767256]]
****************************************
A1: [[5.04506448]
 [7.34767256]]
W2: [[0.30350483 0.43988009]
 [0.3229775  0.47402023]]
b2: [[0.03320586]
 [0.03646999]]
----------------------------------------
A2: [[3.93754019]
 [5.73863884]]
****************************************
A0: [[7]
 [9]]
W1: [[0.30397432 0.44034958]
 [0.32353801 0.47458074]]
b1: [[0.03326455]
 [0.03654005]]
----------------------------------------
A1: [[5.0729268 ]
 [7.39021373]]
****************************************
A1: [[5.0729268 ]
 [7.39021373]]
W2: [[0.30397432 0.44034958]
 [0.32353801 0.47458074]]
b2: [[0.03326455]
 [0.03654005]]
----------------------------------------
A2: [[3.96631901]
 [5.77765431]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.31092464 0.44928571]
 [0.33187573 0.48530067]]
b1: [[0.03425745]
 [0.03773116]]
----------------------------------------
A1: [[5.21856264]
 [7.58645216]]
****************************************
A1: [[5.21856264]
 [7.58645216]]
W2: [[0.31092464 0.44928571]
 [0.33187573 0.48530067]]
b2: [[0.03425745]
 [0.03773116]]
----------------------------------------
A2: [[4.17459654]
 [6.06406712]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.32186233 0.4675152 ]
 [0.34510283 0.50734583]]
b1: [[0.0360804 ]
 [0.03993567]]
----------------------------------------
A1: [[5.78662604]
 [8.46566167]]
****************************************
A1: [[5.78662604]
 [8.46566167]]
W2: [[0.32186233 0.4675152 ]
 [0.34510283 0.50734583]]
b2: [[0.0360804 ]
 [0.03993567]]
----------------------------------------
A2: [[4.82010117]
 [7.04028949]]
****************************************
Epoch -  5 Loss -  2.2891135753499636

{'W1': array([[0.33329713, 0.49495871],
        [0.35907058, 0.54086843]]),
 'b1': array([[0.03836736],
        [0.04272922]]),
 'W2': array([[0.52455618],
        [0.64075209]]),
 'b2': array([[0.64511188],
        [0.        ]])}

## Verifying using Keras

In [49]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [48]:
import tensorflow 
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

D:\JUPYTER NOTEBOOK\DEEP LEARNING\dl_env\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [53]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

D:\JUPYTER NOTEBOOK\DEEP LEARNING\dl_env\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [54]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [55]:
model.get_weights()

[array([[-0.5820425 , -0.2687834 ],
        [ 0.12844956, -1.218205  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.2911595 ],
        [ 0.59347236]], dtype=float32),
 array([0.], dtype=float32)]

In [56]:
new_weights = [np.array([[0.1, 0.1],
                        [0.1, 0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [57]:
model.get_weights()

[array([[-0.5820425 , -0.2687834 ],
        [ 0.12844956, -1.218205  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.2911595 ],
        [ 0.59347236]], dtype=float32),
 array([0.], dtype=float32)]

In [58]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [59]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 168.6881
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 165.5149
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 162.2778
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 159.2176
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 156.2141
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 152.8976
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 150.0637
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.0390
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 144.0972
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 141.0683
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.3571
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 135.3514
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 132.7654
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 130.0794
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.1727
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 124.6371
Epoch 17/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 122.0904
Epoch 18/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 119.3842
Epoch 19/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.9056
Epoch 20/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 114.5061
Epoch 21/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 111.8830
Epoch 22/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 109.4812
Epoch 23/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 107.0899
Epoch 24/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 104.8335
Epoch 25/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.6448
Epoch 26/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 100.1777
Epoch 27/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 98.0473
Epoch 28/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 95.7302
Epoch 29/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.6540
Epoch 30/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.3979
Epoch 31/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.3291
Epoch 32/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 87.3839
Epoch 33/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 85.2626
Epoch 34/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 83.2469
Epoch 35/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.1815
Epoch 36/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.4185
Epoch 37/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.4896
Epoch 38/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 75.4751
Epoch 39/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 73.5997
Epoch 40/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0118
Epoch 41/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 70.2305
Epoch 42/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68.3718
Epoch 43/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.7197
Epoch 44/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.9620
Epoch 45/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 63.2250
Epoch 46/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 61.6309
Epoch 47/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 60.1345
Epoch 48/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.5019
Epoch 49/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 56.9757
Epoch 50/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 55.4577
Epoch 51/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.0039
Epoch 52/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.5537
Epoch 53/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.2028
Epoch 54/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 49.8617
Epoch 55/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 48.3421
Epoch 56/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 46.9713
Epoch 57/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 45.7114
Epoch 58/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 44.4147
Epoch 59/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 43.3270
Epoch 60/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 41.8841
Epoch 61/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 40.8656
Epoch 62/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 39.5433
Epoch 63/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 38.5045
Epoch 64/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 37.2812
Epoch 65/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 36.2340
Epoch 66/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 35.1300
Epoch 67/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 34.0521
Epoch 68/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33.0549
Epoch 69/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 32.1940
Epoch 70/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 31.1256
Epoch 71/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30.2084
Epoch 72/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 29.2819
Epoch 73/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 28.3420
Epoch 74/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 27.5627
Epoch 75/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.6261

In [60]:
model.get_weights()

[array([[-0.8664538 , -0.0538058 ],
        [-0.14386949, -1.011315  ]], dtype=float32),
 array([-0.281122  ,  0.21313033], dtype=float32),
 array([[-0.598362 ],
        [ 0.3775079]], dtype=float32),
 array([0.2376259], dtype=float32)]

# Classification Problem

In [61]:
 df1 = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [62]:
df1

   cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [63]:
def initialize_parameters(layer_dims):
  
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      

  return parameters

In [64]:
# Utility Functions
def sigmoid(Z):
  
  A = 1/(1+np.exp(-Z))

  return A

In [65]:
def linear_forward(A_prev, W, b):
  
  Z = np.dot(W.T, A_prev) + b

  A = sigmoid(Z)
  
  return A

In [66]:
# L-layer feed forward

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
          
  return A,A_prev

In [67]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [73]:
X = df1[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.613402628898913

{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [74]:
X = df1[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.568725622654268

{'W1': array([[0.10000937, 0.10001059],
        [0.10000937, 0.10001059]]),
 'b1': array([[1.24770113e-06],
        [1.24770113e-06]]),
 'W2': array([[0.10007424],
        [0.10007424]]),
 'b2': array([[0.10011761]])}

In [75]:
X = df1[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.8353333695154365

{'W1': array([[0.10000463, 0.10000267],
        [0.10000463, 0.10000267]]),
 'b1': array([[4.56125378e-07],
        [4.56135584e-07]]),
 'W2': array([[0.10002712],
        [0.10002712]]),
 'b2': array([[0.09997049]])}

In [76]:
X = df1[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.8238180133031612

{'W1': array([[0.09999911, 0.09999716],
        [0.09999911, 0.09999716]]),
 'b1': array([[-6.47175329e-07],
        [-6.47175081e-07]]),
 'W2': array([[0.09998609],
        [0.09998609]]),
 'b2': array([[0.09992997]])}

In [77]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df1[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df1[['placed']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.7103199085929446
Epoch -  2 Loss -  0.6991702892802629
Epoch -  3 Loss -  0.6991679314811485
Epoch -  4 Loss -  0.6991655746710999
Epoch -  5 Loss -  0.6991632188496667
Epoch -  6 Loss -  0.699160864016399
Epoch -  7 Loss -  0.6991585101708473
Epoch -  8 Loss -  0.6991561573125619
Epoch -  9 Loss -  0.6991538054410936
Epoch -  10 Loss -  0.6991514545559935
Epoch -  11 Loss -  0.6991491046568126
Epoch -  12 Loss -  0.6991467557431024
Epoch -  13 Loss -  0.6991444078144144
Epoch -  14 Loss -  0.6991420608703007
Epoch -  15 Loss -  0.6991397149103132
Epoch -  16 Loss -  0.6991373699340042
Epoch -  17 Loss -  0.6991350259409265
Epoch -  18 Loss -  0.6991326829306324
Epoch -  19 Loss -  0.6991303409026751
Epoch -  20 Loss -  0.699127999856608
Epoch -  21 Loss -  0.6991256597919842
Epoch -  22 Loss -  0.6991233207083575
Epoch -  23 Loss -  0.6991209826052818
Epoch -  24 Loss -  0.699118645482311
Epoch -  25 Loss -  0.6991163093389996
Epoch -  26 Loss -  0.699113974174902
Epoch -  27 Loss -  0.6991116399895729
Epoch -  28 Loss -  0.6991093067825676
Epoch -  29 Loss -  0.699106974553441
Epoch -  30 Loss -  0.6991046433017485
Epoch -  31 Loss -  0.6991023130270458
Epoch -  32 Loss -  0.699099983728889
Epoch -  33 Loss -  0.6990976554068338
Epoch -  34 Loss -  0.6990953280604367
Epoch -  35 Loss -  0.6990930016892543
Epoch -  36 Loss -  0.6990906762928432
Epoch -  37 Loss -  0.6990883518707602
Epoch -  38 Loss -  0.6990860284225631
Epoch -  39 Loss -  0.6990837059478086
Epoch -  40 Loss -  0.6990813844460546
Epoch -  41 Loss -  0.699079063916859
Epoch -  42 Loss -  0.6990767443597797
Epoch -  43 Loss -  0.6990744257743753
Epoch -  44 Loss -  0.699072108160204
Epoch -  45 Loss -  0.6990697915168249
Epoch -  46 Loss -  0.6990674758437966
Epoch -  47 Loss -  0.6990651611406782
Epoch -  48 Loss -  0.6990628474070294
Epoch -  49 Loss -  0.6990605346424095
Epoch -  50 Loss -  0.6990582228463785

{'W1': array([[0.09994267, 0.09984548],
        [0.09994272, 0.09984548]]),
 'b1': array([[-3.38405750e-05],
        [-3.38419977e-05]]),
 'W2': array([[0.09920806],
        [0.09920816]]),
 'b2': array([[0.09915209]])}

# Classification Using keras

In [79]:
model1 = Sequential()
model1.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

D:\JUPYTER NOTEBOOK\DEEP LEARNING\dl_env\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [80]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (128.00 B)

 Trainable params: 11 (44.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 20 (84.00 B)

In [81]:
model.get_weights()

[array([[-0.8664538 , -0.0538058 ],
        [-0.14386949, -1.011315  ]], dtype=float32),
 array([-0.281122  ,  0.21313033], dtype=float32),
 array([[-0.598362 ],
        [ 0.3775079]], dtype=float32),
 array([0.2376259], dtype=float32),
 array([[0.31964505]], dtype=float32),
 array([0.], dtype=float32)]

In [83]:
new_weights = [np.array([[0.1, 0.1],
                        [0.1, 0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [84]:
model.get_weights()

[array([[-0.8664538 , -0.0538058 ],
        [-0.14386949, -1.011315  ]], dtype=float32),
 array([-0.281122  ,  0.21313033], dtype=float32),
 array([[-0.598362 ],
        [ 0.3775079]], dtype=float32),
 array([0.2376259], dtype=float32),
 array([[0.31964505]], dtype=float32),
 array([0.], dtype=float32)]

In [85]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [89]:
model.fit(df1.iloc[:,0:-1].values,df1['placed'].values,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6437
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6433
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6436
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6432
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6430
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6421
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6424
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6433
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6426
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6420
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6410
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6409
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6405
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6405
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6403
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6403
Epoch 17/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6405
Epoch 18/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6412
Epoch 19/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6395
Epoch 20/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6400
Epoch 21/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6395
Epoch 22/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6392
Epoch 23/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6391
Epoch 24/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6388
Epoch 25/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6388
Epoch 26/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6393
Epoch 27/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6385
Epoch 28/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6382
Epoch 29/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6389
Epoch 30/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6378
Epoch 31/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6379
Epoch 32/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6375
Epoch 33/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6384
Epoch 34/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6381
Epoch 35/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6385
Epoch 36/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6371
Epoch 37/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6371
Epoch 38/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6369
Epoch 39/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6369
Epoch 40/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6375
Epoch 41/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6366
Epoch 42/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6373
Epoch 43/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6372
Epoch 44/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6367
Epoch 45/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6371
Epoch 46/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6367
Epoch 47/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6358
Epoch 48/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6357
Epoch 49/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6355
Epoch 50/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6354